<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AssemblyName>DartsCounter</AssemblyName>
        <PackageId>DartsCounter</PackageId>
        <Title>Darts Counter</Title>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Icons\" />
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Include="..\assets_md\SettingsMain.jpg" Link="Assets\Backgrounds\SettingsMain.jpg" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="NetCoreAudio" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Strings.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Strings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="SoundManagerDarts">
        <HintPath>..\SoundManagerDarts.dll</HintPath>
      </Reference>
    </ItemGroup>

    
</Project>
