//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopUI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DesktopUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        public static string AboutAppMenu {
            get {
                return ResourceManager.GetString("AboutAppMenu", resourceCulture);
            }
        }
        
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        public static string StatsMenu {
            get {
                return ResourceManager.GetString("StatsMenu", resourceCulture);
            }
        }
        
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        public static string NumPlayers {
            get {
                return ResourceManager.GetString("NumPlayers", resourceCulture);
            }
        }
        
        public static string NumScore {
            get {
                return ResourceManager.GetString("NumScore", resourceCulture);
            }
        }
        
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        public static string PauseMenu {
            get {
                return ResourceManager.GetString("PauseMenu", resourceCulture);
            }
        }
        
        public static string MusicMMenu {
            get {
                return ResourceManager.GetString("MusicMMenu", resourceCulture);
            }
        }
        
        public static string ButtonGameOn {
            get {
                return ResourceManager.GetString("ButtonGameOn", resourceCulture);
            }
        }
        
        public static string ButtonTraining {
            get {
                return ResourceManager.GetString("ButtonTraining", resourceCulture);
            }
        }
        
        public static string ButtonTournament {
            get {
                return ResourceManager.GetString("ButtonTournament", resourceCulture);
            }
        }
        
        public static string ButtonDetailOfTournament {
            get {
                return ResourceManager.GetString("ButtonDetailOfTournament", resourceCulture);
            }
        }
        
        public static string AppSettingsMain {
            get {
                return ResourceManager.GetString("AppSettingsMain", resourceCulture);
            }
        }
        
        public static string SettingsNameAndColors {
            get {
                return ResourceManager.GetString("SettingsNameAndColors", resourceCulture);
            }
        }
        
        public static string SettingsPlayerName {
            get {
                return ResourceManager.GetString("SettingsPlayerName", resourceCulture);
            }
        }
        
        public static string SettingsPlayerColor {
            get {
                return ResourceManager.GetString("SettingsPlayerColor", resourceCulture);
            }
        }
        
        public static string SettingsOthers {
            get {
                return ResourceManager.GetString("SettingsOthers", resourceCulture);
            }
        }
        
        public static string SettingsLang {
            get {
                return ResourceManager.GetString("SettingsLang", resourceCulture);
            }
        }
        
        public static string SettingsWallpaper {
            get {
                return ResourceManager.GetString("SettingsWallpaper", resourceCulture);
            }
        }
        
        public static string SettingsStartupMusic {
            get {
                return ResourceManager.GetString("SettingsStartupMusic", resourceCulture);
            }
        }
        
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        public static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        public static string SettingsDefault {
            get {
                return ResourceManager.GetString("SettingsDefault", resourceCulture);
            }
        }
        
        public static string SettingsTransparency {
            get {
                return ResourceManager.GetString("SettingsTransparency", resourceCulture);
            }
        }
        
        public static string SettingsSoundEffects {
            get {
                return ResourceManager.GetString("SettingsSoundEffects", resourceCulture);
            }
        }
        
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        public static string SettingsThemeSystem {
            get {
                return ResourceManager.GetString("SettingsThemeSystem", resourceCulture);
            }
        }
        
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        public static string SettingsUpdate {
            get {
                return ResourceManager.GetString("SettingsUpdate", resourceCulture);
            }
        }
        
        public static string MenuDartboard {
            get {
                return ResourceManager.GetString("MenuDartboard", resourceCulture);
            }
        }
        
        public static string SettingsTransparencyIntensity {
            get {
                return ResourceManager.GetString("SettingsTransparencyIntensity", resourceCulture);
            }
        }
        
        public static string AppReleaseNotesErr {
            get {
                return ResourceManager.GetString("AppReleaseNotesErr", resourceCulture);
            }
        }
        
        public static string AppReleaseNotesLoad {
            get {
                return ResourceManager.GetString("AppReleaseNotesLoad", resourceCulture);
            }
        }
        
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        public static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        public static string UpdateUpToDate {
            get {
                return ResourceManager.GetString("UpdateUpToDate", resourceCulture);
            }
        }
        
        public static string DartboardThrown {
            get {
                return ResourceManager.GetString("DartboardThrown", resourceCulture);
            }
        }
        
        public static string DartboardClear {
            get {
                return ResourceManager.GetString("DartboardClear", resourceCulture);
            }
        }
        
        public static string DartboardConfirm {
            get {
                return ResourceManager.GetString("DartboardConfirm", resourceCulture);
            }
        }
        
        public static string DartboardCurrentRound {
            get {
                return ResourceManager.GetString("DartboardCurrentRound", resourceCulture);
            }
        }
        
        public static string DartboardOutside {
            get {
                return ResourceManager.GetString("DartboardOutside", resourceCulture);
            }
        }
        
        public static string DartboardSingle {
            get {
                return ResourceManager.GetString("DartboardSingle", resourceCulture);
            }
        }
        
        public static string DartboardDouble {
            get {
                return ResourceManager.GetString("DartboardDouble", resourceCulture);
            }
        }
        
        public static string DartboardTreble {
            get {
                return ResourceManager.GetString("DartboardTreble", resourceCulture);
            }
        }
        
        public static string DartboardUpNext {
            get {
                return ResourceManager.GetString("DartboardUpNext", resourceCulture);
            }
        }
        
        public static string StatisticsCreatePlayer {
            get {
                return ResourceManager.GetString("StatisticsCreatePlayer", resourceCulture);
            }
        }
        
        public static string StatisticsCreateButton {
            get {
                return ResourceManager.GetString("StatisticsCreateButton", resourceCulture);
            }
        }
        
        public static string StatisticsManage {
            get {
                return ResourceManager.GetString("StatisticsManage", resourceCulture);
            }
        }
        
        public static string StatisticsRemove {
            get {
                return ResourceManager.GetString("StatisticsRemove", resourceCulture);
            }
        }
        
        public static string StatisticsRename {
            get {
                return ResourceManager.GetString("StatisticsRename", resourceCulture);
            }
        }
        
        public static string StatisticsMatchesCount {
            get {
                return ResourceManager.GetString("StatisticsMatchesCount", resourceCulture);
            }
        }
        
        public static string StatisticsVictoryCount {
            get {
                return ResourceManager.GetString("StatisticsVictoryCount", resourceCulture);
            }
        }
        
        public static string DuelSetMatch {
            get {
                return ResourceManager.GetString("DuelSetMatch", resourceCulture);
            }
        }
        
        public static string DuelSetMainText {
            get {
                return ResourceManager.GetString("DuelSetMainText", resourceCulture);
            }
        }
        
        public static string DuelFirstTeam {
            get {
                return ResourceManager.GetString("DuelFirstTeam", resourceCulture);
            }
        }
        
        public static string DuelSecondTeam {
            get {
                return ResourceManager.GetString("DuelSecondTeam", resourceCulture);
            }
        }
        
        public static string DuelPlayerOne {
            get {
                return ResourceManager.GetString("DuelPlayerOne", resourceCulture);
            }
        }
        
        public static string DuelPlayerTwo {
            get {
                return ResourceManager.GetString("DuelPlayerTwo", resourceCulture);
            }
        }
        
        public static string DuelPlayerThree {
            get {
                return ResourceManager.GetString("DuelPlayerThree", resourceCulture);
            }
        }
        
        public static string DuelPlayerFour {
            get {
                return ResourceManager.GetString("DuelPlayerFour", resourceCulture);
            }
        }
        
        public static string DuelSetSets {
            get {
                return ResourceManager.GetString("DuelSetSets", resourceCulture);
            }
        }
        
        public static string DuelFirstTo {
            get {
                return ResourceManager.GetString("DuelFirstTo", resourceCulture);
            }
        }
        
        public static string DuelWins {
            get {
                return ResourceManager.GetString("DuelWins", resourceCulture);
            }
        }
        
        public static string DuelSetNumberOfLegs {
            get {
                return ResourceManager.GetString("DuelSetNumberOfLegs", resourceCulture);
            }
        }
        
        public static string DuelSetNumberOfSets {
            get {
                return ResourceManager.GetString("DuelSetNumberOfSets", resourceCulture);
            }
        }
        
        public static string DartboardMain {
            get {
                return ResourceManager.GetString("DartboardMain", resourceCulture);
            }
        }
        
        public static string TrainingThrown {
            get {
                return ResourceManager.GetString("TrainingThrown", resourceCulture);
            }
        }
        
        public static string TrainingNotThrown {
            get {
                return ResourceManager.GetString("TrainingNotThrown", resourceCulture);
            }
        }
        
        public static string TrainingTotal {
            get {
                return ResourceManager.GetString("TrainingTotal", resourceCulture);
            }
        }
        
        public static string TrainingSingleThrows {
            get {
                return ResourceManager.GetString("TrainingSingleThrows", resourceCulture);
            }
        }
        
        public static string TrainingDoubleThrows {
            get {
                return ResourceManager.GetString("TrainingDoubleThrows", resourceCulture);
            }
        }
        
        public static string TrainingTrebleThrows {
            get {
                return ResourceManager.GetString("TrainingTrebleThrows", resourceCulture);
            }
        }
        
        public static string TrainingRandomThrows {
            get {
                return ResourceManager.GetString("TrainingRandomThrows", resourceCulture);
            }
        }
        
        public static string TrainingCheckoutThrows {
            get {
                return ResourceManager.GetString("TrainingCheckoutThrows", resourceCulture);
            }
        }
        
        public static string TrainingLevel {
            get {
                return ResourceManager.GetString("TrainingLevel", resourceCulture);
            }
        }
        
        public static string TrainingNotThrownNext {
            get {
                return ResourceManager.GetString("TrainingNotThrownNext", resourceCulture);
            }
        }
        
        public static string TrainingThrownNext {
            get {
                return ResourceManager.GetString("TrainingThrownNext", resourceCulture);
            }
        }
        
        public static string StatisticsTypeName {
            get {
                return ResourceManager.GetString("StatisticsTypeName", resourceCulture);
            }
        }
        
        public static string StatisticsDetails {
            get {
                return ResourceManager.GetString("StatisticsDetails", resourceCulture);
            }
        }
        
        public static string StatisticsAverage {
            get {
                return ResourceManager.GetString("StatisticsAverage", resourceCulture);
            }
        }
        
        public static string StatisticsHighestOut {
            get {
                return ResourceManager.GetString("StatisticsHighestOut", resourceCulture);
            }
        }
        
        public static string StatisticsYearPlaceholder {
            get {
                return ResourceManager.GetString("StatisticsYearPlaceholder", resourceCulture);
            }
        }
        
        public static string TournamentMain {
            get {
                return ResourceManager.GetString("TournamentMain", resourceCulture);
            }
        }
        
        public static string TournamentNumPlayers {
            get {
                return ResourceManager.GetString("TournamentNumPlayers", resourceCulture);
            }
        }
        
        public static string TournamentPrepare {
            get {
                return ResourceManager.GetString("TournamentPrepare", resourceCulture);
            }
        }
        
        public static string TournamentRoster {
            get {
                return ResourceManager.GetString("TournamentRoster", resourceCulture);
            }
        }
        
        public static string TournamentSetupErrorPlayers {
            get {
                return ResourceManager.GetString("TournamentSetupErrorPlayers", resourceCulture);
            }
        }
        
        public static string DuelError {
            get {
                return ResourceManager.GetString("DuelError", resourceCulture);
            }
        }
        
        public static string TournamentPlayer {
            get {
                return ResourceManager.GetString("TournamentPlayer", resourceCulture);
            }
        }
        
        public static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        public static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string ManualUpdate {
            get {
                return ResourceManager.GetString("ManualUpdate", resourceCulture);
            }
        }
        
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        public static string InternetNot {
            get {
                return ResourceManager.GetString("InternetNot", resourceCulture);
            }
        }
        
        public static string StatisticsAchievements {
            get {
                return ResourceManager.GetString("StatisticsAchievements", resourceCulture);
            }
        }
        
        public static string AchCupTitle {
            get {
                return ResourceManager.GetString("AchCupTitle", resourceCulture);
            }
        }

        public static string AchCupImage {
            get {
                return ResourceManager.GetString("AchCupImage", resourceCulture);
            }
        }
        
        public static string AchCup20Title {
            get {
                return ResourceManager.GetString("AchCup20Title", resourceCulture);
            }
        }

        public static string AchCup20Image {
            get {
                return ResourceManager.GetString("AchCup20Image", resourceCulture);
            }
        }
        
        public static string AchCup100Title {
            get {
                return ResourceManager.GetString("AchCup100Title", resourceCulture);
            }
        }

        public static string AchCup100Image {
            get {
                return ResourceManager.GetString("AchCup100Image", resourceCulture);
            }
        }
        
        public static string AchMore100Title {
            get {
                return ResourceManager.GetString("AchMore100Title", resourceCulture);
            }
        }

        public static string AchMore100Image {
            get {
                return ResourceManager.GetString("AchMore100Image", resourceCulture);
            }
        }
        
        public static string Ach180Title {
            get {
                return ResourceManager.GetString("Ach180Title", resourceCulture);
            }
        }

        public static string Ach180Image {
            get {
                return ResourceManager.GetString("Ach180Image", resourceCulture);
            }
        }
        
        public static string ToolTipToggleTimer {
            get {
                return ResourceManager.GetString("ToolTipToggleTimer", resourceCulture);
            }
        }
        
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        public static string StatisticsImport {
            get {
                return ResourceManager.GetString("StatisticsImport", resourceCulture);
            }
        }
        
        public static string StatisticsImportSelect {
            get {
                return ResourceManager.GetString("StatisticsImportSelect", resourceCulture);
            }
        }
        
        public static string SqliteDb {
            get {
                return ResourceManager.GetString("SqliteDb", resourceCulture);
            }
        }
        
        public static string Allfiles {
            get {
                return ResourceManager.GetString("Allfiles", resourceCulture);
            }
        }
    }
}
